import { Button, VerticalBox, LineEdit } from "std-widgets.slint";


component CalculateButton {
    callback cbk;
    Button {
        text: "Calculate";
        primary: true;
        height: 32px;
        clicked => {
            cbk()
        }
    }
}

export component AppWindow inherits Window {
    callback divide-income(string);
    in property <string> results: "";
    background: #444444;
    GridLayout {
        padding: 32px;
        spacing: 16px;
        Row {
            Text {
                text: "total income";
                horizontal-alignment: center;
                font-size: 24px;
                font-weight: 900;
                color: #eeeeee;
            }
        }

        Row {
            income := LineEdit {
                font-size: 16px;
                placeholder-text: "Enter your income";
                height: 32px;
            }
        }

        Row {
            CalculateButton {
                cbk => {
                    divide-income(income.text)
                }
            }
        }

        Row {
            VerticalBox {
                Rectangle {
                    height: 100px;
                    background: #f2f2f2;
                    Text {
                        color: black;
                        font-size: 16px;
                        font-weight: 500;
                        text: root.results;
                    }
                }
            }
        }
    }
}
